Student_Registration_Theme/Areas/Country/Controllers/LOC_CountryController.cs
using Microsoft.AspNetCore.Mvc;
using Student_Registration_Theme.Areas.Country.Models;
using System.Data;
using System.Data.SqlClient;

namespace Student_Registration_Theme.Areas.Country.Controllers
{
    [Area("Country")]
    public class LOC_CountryController : Controller
    {
        private IConfiguration Configuration;

        public LOC_CountryController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IActionResult LOC_CountryList()
        {

            string connection_string = this.Configuration.GetConnectionString("MyConnectionString");
            SqlConnection conn = new SqlConnection(connection_string);
            conn.Open();

            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_LOC_Country_SelectAll";

            SqlDataReader reader = cmd.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(reader);

            return View(dt);
        }

        public IActionResult Add()
        {
            return View("LOC_CountryAddEdit");
        }

        public IActionResult LOC_CountryAddEdit(int? CountryID = 0)
        {
            Console.WriteLine("CountryID : ", CountryID);
            string connection_string = this.Configuration.GetConnectionString("MyConnectionString");
            SqlConnection conn = new SqlConnection(connection_string);
            conn.Open();

            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_LOC_Country_SelectByPK";
            cmd.Parameters.AddWithValue("@CountryID", CountryID);

            SqlDataReader reader = cmd.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(reader);

            LOC_CountryModel CM = new LOC_CountryModel();

            foreach(DataRow dr in dt.Rows)
            {
                CM.CountryID = Convert.ToInt32(@dr["CountryID"]);
                CM.CountryName = @dr["CountryName"].ToString();
                CM.CountryCode = @dr["CountryCode"].ToString();
            }

            return View("LOC_CountryAddEdit" , CM);
        }

        public IActionResult LOC_CountrySave(LOC_CountryModel CM)
        {

                string connection_string = this.Configuration.GetConnectionString("MyConnectionString");
                SqlConnection conn = new SqlConnection(connection_string);
                conn.Open();

                SqlCommand cmd = conn.CreateCommand();
                cmd.CommandType = CommandType.StoredProcedure;

                /* DataTable dt = new DataTable();*/

                if (CM.CountryID == 0)
                {
                    cmd.CommandText = "PR_LOC_Country_Insert";
                }
                else
                {
                    cmd.CommandText = "PR_LOC_Country_UpdateByPK";
                    cmd.Parameters.AddWithValue("@CountryID", CM.CountryID);
                }

                cmd.Parameters.AddWithValue("@CountryName", CM.CountryName);
                cmd.Parameters.AddWithValue("@countryCode", CM.CountryCode);

                cmd.ExecuteNonQuery();
                conn.Close();

                return RedirectToAction("LOC_CountryList");

            //return View("LOC_CountryAddEdit",CM);
        }

        public IActionResult DeleteCountry(int CountryID)
        {

            string connection_string = this.Configuration.GetConnectionString("MyConnectionString");
            SqlConnection conn = new SqlConnection(connection_string);
            conn.Open();

            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_LOC_Country_DeleteByPK";
            cmd.Parameters.AddWithValue("@CountryID", CountryID);
            cmd.ExecuteNonQuery();

            return RedirectToAction("");
        }

        public IActionResult LOC_CountryFilter(string? CountryName, string? CountryCode)
        {

            string connection_string = this.Configuration.GetConnectionString("MyConnectionString");
            SqlConnection conn = new SqlConnection(connection_string);
            conn.Open();

            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_LOC_Country_Filter";

            if(CountryName == null)
            {
                CountryName = DBNull.Value.ToString();
            }

            if (CountryCode == null)
            {
                CountryCode = DBNull.Value.ToString();
            }

            cmd.Parameters.AddWithValue("@CountryName", CountryName);
            cmd.Parameters.AddWithValue("@CountryCode", CountryCode);

            SqlDataReader reader = cmd.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(reader);

            return View("LOC_CountryList" , dt);
        }

    }
}

Student_Registration_Theme/Areas/Country/Views/LOC_Country/LOC_CountryAddEdit.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Student_Registration_Theme.Areas.Country.Models.LOC_CountryModel;

<div class="container border border-gray rounded p-5 shadow">

    <h2><i class="bi bi-gear me-2 pb-5" style="font-size: 25px"></i>Country</h2>

    <hr />

    <form class="pt-3" method="post" asp-area="Country" asp-controller="LOC_Country" asp-action="LOC_CountrySave">

        <div class="col my-4">
            <input type="text" class="form-control" asp-for= "CountryName" placeholder="Country Name" aria-label="First name">
        </div>

        <div class="col my-4">
            <input type="text" class="form-control" asp-for="CountryCode" placeholder="Country Code" aria-label="Last name">
        </div>

        <div class="col mt-4">
            
            <input type="hidden" name="CountryID" value = "@Model.CountryID" />
            <button class="btn btn-primary" type="submit">Submit</button>

        </div>

    </form>

</div>

Student_Registration_Theme/Areas/Country/Views/LOC_Country/LOC_CountryList.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using System.Data;
@model System.Data.DataTable;

<style>

    .line {
        width: 50%;
        height: 1px;
        border: 1px solid rgba(0, 0, 0, 0.1);
    }

</style>

<div class="pagetitle my-4 mx-2">
    <h1>Dashboard</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">Country</li>
        </ol>
    </nav>
</div><!-- End Page Title -->

<div class="border rounded p-5 shadow">

    <div class="d-flex justify-content-between align-items-center">

        <h5 class="fw-bold"><i class="bi bi-gear me-2" style="font-size: 20px"></i>COUNTRY LIST</h5>
        <a asp-area="Country" asp-controller="LOC_Country" asp-action="LOC_CountryAddEdit">
            <button class="btn bg-success text-white py-2"><i class="bi bi-plus-circle me-2"></i>ADD COUNTRY</button>
        </a>

    </div>

    <hr />

    @*<div class="border border-dark rounded ps-3 pe-5 py-2 ms-auto w-25 my-3">

    Search here

    </div>*@

    @*<input type="text" placeholder="Search here" class="border border-dark d-block rounded ps-3 pe-5 py-2 ms-auto my-3" />*@

    <form asp-area="Country" asp-controller="LOC_Country">
        <div class="row">
            <div class="w-25 ms-auto my-3">
                <label class="visually-hidden" for="autoSizingInputGroup">Username</label>
                <div class="input-group">
                    <div class="input-group-text bg-transparent" style="font-size: 15px"><i class="bi bi-search"></i></div>
                    <input type="text" class="form-control" id="CountryName" name="CountryName" placeholder="Search Country Name here">
                    @* <input type="hidden" name="CountryName" value="CountryName" />*@
                </div>
            </div>

            <div class="w-25 my-3">
                <label class="visually-hidden" for="autoSizingInputGroup">Username</label>
                <div class="input-group">
                    <div class="input-group-text bg-transparent" style="font-size: 15px"><i class="bi bi-search"></i></div>
                    <input type="text" class="form-control" id="CountryCode" name="CountryCode" placeholder="Search Country Code here">
                    @*<input type="hidden" name="CountryCode" value="CountryCode" />*@
                </div>
            </div>

            <div class="w-auto my-3">
                <div class="input-group">
                    <input type="submit"asp-action="LOC_CountryFilter" class="btn btn-primary" id="" value="Apply Filter" placeholder="Search Country Code here">
                </div>
            </div>

            <div class="w-auto my-3">
                <div class="input-group">
                    <input type="submit"asp-action="LOC_CountryList" class="btn text-white" style="background-color: rgba(10 , 10 , 10 , 0.5)" id="" value="Clear Filter" placeholder="Search Country Code here">
                </div>
            </div>

        </div>
    </form>

    <div class="line ms-auto my-3"></div>

    <div>
        <div class="w-25 ms-auto my-3 col">
            <p class="text-secondary">
                <span class="ms-1 me-2">&#x2022</span> Search With JQuery
            </p>
            <label class="visually-hidden" for="autoSizingInputGroup">Username</label>
            <div class="input-group">
                <div class="input-group-text bg-transparent" style="font-size: 15px"><i class="bi bi-search"></i></div>
                <input type="text" class="form-control" id="myInput" placeholder="Search here">
            </div>
        </div>

    </div>

    <div>

        <table class="table table-striped table-bordered table-responsive">
            <thead>
                <tr>
                    @*<th scope="col">CountryId</th>*@
                    <th scope="col" class="text-center">CountryName</th>
                    <th scope="col" class="text-center">CountryCode</th>
                    <th scope="col" class="text-center">Created</th>
                    <th scope="col" class="text-center">Modified</th>
                    <th scope="col" class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody id="myTable">

                @foreach (DataRow dr in Model.Rows)
                {

                    <tr>
                        @*<td class="text-center">@dr["CountryID"]</td>*@
                        <td class="text-center">@dr["CountryName"]</td>
                        <td class="text-center">@dr["CountryCode"]</td>
                        <td class="text-center">@dr["Created"]</td>
                        <td class="text-center">@dr["Modified"]</td>
                        <td class="text-center d-flex justify-content-center align-items-center">

                            <form method="post" asp-area="Country" asp-controller="LOC_Country" asp-action="LOC_CountryAddEdit">
                                <input type="hidden" name="CountryID" value="@Convert.ToInt32(@dr["CountryID"])" />
                                <button type="submit" class="btn btn-primary py-1 me-2"><i class="bi bi-pen" style="font-size: 14px"></i></button>
                            </form>
                            <form method="post" asp-area="Country" asp-controller="LOC_Country" asp-action="DeleteCountry">
                                <input type="hidden" name="CountryID" value="@Convert.ToInt32(@dr["CountryID"])" />
                                <button type="submit" class="btn btn-danger py-1"><i class="bi bi-trash" style="font-size: 14px"></i></button>
                            </form>

                        </td>
                    </tr>
                }

            </tbody>
        </table>

    </div>

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

@section Scripts {

    <script>
        $(document).ready(function () {
            //alert("Hello");
            $("#myInput").on("keyup", function () {
                //alert("Function");
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>

}