Student_Registration_Theme/Areas/Branch/Controllers/MST_BranchController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using Student_Registration_Theme.Areas.Branch.Models;

namespace Student_Registration_Theme.Areas.Branch.Controllers
{
    [Area("Branch")]
    public class MST_BranchController : Controller
    {
        public IConfiguration Configuration;
        public MST_BranchController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IActionResult MST_BranchList()
        {
            string connection_string = this.Configuration.GetConnectionString("MyConnectionString");
            SqlConnection conn = new SqlConnection(connection_string);
            conn.Open();

            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_MST_Branch_SelectAll";

            SqlDataReader reader = cmd.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(reader);
            conn.Close();
            return View(dt);
        }

        public IActionResult MST_BranchSave(MST_BranchModel bm)
        {
            string connection_string = this.Configuration.GetConnectionString("MyConnectionString");
            SqlConnection conn = new SqlConnection(connection_string);
            conn.Open();

            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            if (bm.BranchID == 0)
            {
                cmd.CommandText = "PR_MST_Branch_Insert";
            }
            else
            {
                cmd.CommandText = "PR_MST_Branch_UpdateByPK";
                cmd.Parameters.AddWithValue("@BranchID", bm.BranchID);
            }
            cmd.Parameters.AddWithValue("@BranchName", bm.BranchName);
            cmd.Parameters.AddWithValue("@BranchCode", bm.BranchCode);
            cmd.ExecuteNonQuery();
            conn.Close();
            return RedirectToAction("MST_BranchList");
        }

        public IActionResult MST_BranchAddEdit(int? BranchID = 0)
        {
            string connection_string = this.Configuration.GetConnectionString("MyConnectionString");
            SqlConnection conn = new SqlConnection(connection_string);
            conn.Open();

            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_MST_Branch_SelectByPK";
            cmd.Parameters.AddWithValue("@BranchID", BranchID);

            SqlDataReader reader = cmd.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(reader);
            conn.Close();

            MST_BranchModel bm = new MST_BranchModel();

            foreach (DataRow dr in dt.Rows)
            {
                bm.BranchID = Convert.ToInt32(dr["BranchID"]);
                bm.BranchName = dr["BranchName"].ToString();
                bm.BranchCode = dr["BranchCode"].ToString();
            }

            return View("MST_BranchAddEdit", bm);
        }

        public IActionResult DeleteBranch(int? BranchID)
        {
            string connection_string = this.Configuration.GetConnectionString("MyConnectionString");
            SqlConnection conn = new SqlConnection(connection_string);
            conn.Open();

            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_MST_Branch_DeleteByPK";
            cmd.Parameters.AddWithValue("@BranchID", BranchID);
            cmd.ExecuteNonQuery();
            return RedirectToAction("MST_BranchList");
        }

        public IActionResult MST_BranchFilter(string? BranchName, string? BranchCode)
        {

            string connection_string = this.Configuration.GetConnectionString("MyConnectionString");
            SqlConnection conn = new SqlConnection(connection_string);
            conn.Open();

            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_Branch_Filter";

            if (BranchName == null)
            {
                BranchName = DBNull.Value.ToString();
            }

            if (BranchCode == null)
            {
                BranchCode = DBNull.Value.ToString();
            }

            cmd.Parameters.AddWithValue("@BranchName", BranchName);
            cmd.Parameters.AddWithValue("@BranchCode", BranchCode);

            SqlDataReader reader = cmd.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(reader);

            return View("MST_BranchList", dt);
        }
    }
}

Student_Registration_Theme/Areas/Branch/Views/MST_Branch/MST_BranchAddEdit.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Student_Registration_Theme.Areas.Branch.Models.MST_BranchModel;

<div class="container border border-gray rounded p-5 shadow">

    <h2><i class="bi bi-gear me-2 pb-5" style="font-size: 25px"></i>Branch</h2>

    <hr />

    <form class="pt-3" method="post" asp-area="Branch" asp-controller="MST_Branch" asp-action="MST_BranchSave">

        <div class="col my-4">
            <input type="text" class="form-control" asp-for="BranchName" placeholder="Branch Name" aria-label="First name">
        </div>

        <div class="col my-4">
            <input type="text" class="form-control" asp-for="BranchCode" placeholder="Branch Code" aria-label="Last name">
        </div>

        <div class="col mt-4">

            <input type="hidden" name="BranchID" value="@Model.BranchID" />
            <button class="btn btn-primary" type="submit">Submit</button>

        </div>

    </form>

</div>

Student_Registration_Theme/Areas/Branch/Views/MST_Branch/MST_BranchList.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using System.Data;
@model System.Data.DataTable;

<style>

    .line {
        width: 50%;
        height: 1px;
        border: 1px solid rgba(0, 0, 0, 0.1);
    }

</style>

<div class="pagetitle my-4 mx-2">
    <h1>Dashboard</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">Branch</li>
        </ol>
    </nav>
</div><!-- End Page Title -->

<div class="border rounded p-5 shadow">

    <div class="d-flex justify-content-between align-items-center">

        <h5 class="fw-bold"><i class="bi bi-gear me-2" style="font-size: 20px"></i>BRANCH LIST</h5>
        <a asp-area="Branch" asp-controller="MST_Branch" asp-action="MST_BranchAddEdit">
            <button class="btn bg-success text-white py-2"><i class="bi bi-plus-circle me-2"></i>ADD BRANCH</button>
        </a>

    </div>

    <hr />

    @*<div class="border border-dark rounded ps-3 pe-5 py-2 ms-auto w-25 my-3">

    Search here

    </div>*@

    @*<input type="text" placeholder="Search here" class="border border-dark d-block rounded ps-3 pe-5 py-2 ms-auto my-3" />*@

    <form asp-area="Branch" asp-controller="MST_Branch">
        <div class="row">
            <div class="w-25 ms-auto my-3">
                <label class="visually-hidden" for="autoSizingInputGroup">Username</label>
                <div class="input-group">
                    <div class="input-group-text bg-transparent" style="font-size: 15px"><i class="bi bi-search"></i></div>
                    <input type="text" class="form-control" id="BranchName" name="BranchName" placeholder="Search Branch Name here">
                    @* <input type="hidden" name="CountryName" value="CountryName" />*@
                </div>
            </div>

            <div class="w-25 my-3">
                <label class="visually-hidden" for="autoSizingInputGroup">Username</label>
                <div class="input-group">
                    <div class="input-group-text bg-transparent" style="font-size: 15px"><i class="bi bi-search"></i></div>
                    <input type="text" class="form-control" id="BranchCode" name="BranchCode" placeholder="Search Branch Code here">
                    @*<input type="hidden" name="CountryCode" value="CountryCode" />*@
                </div>
            </div>

            <div class="w-auto my-3">
                <div class="input-group">
                    <input type="submit" asp-action="MST_BranchFilter" class="btn btn-primary" id="" value="Apply Filter" placeholder="Search Branch Code here">
                </div>
            </div>

            <div class="w-auto my-3">
                <div class="input-group">
                    <input type="submit" asp-action="MST_BranchList" class="btn text-white" style="background-color: rgba(10 , 10 , 10 , 0.5)" id="" value="Clear Filter" placeholder="Search Country Code here">
                </div>
            </div>

        </div>
    </form>

    <div class="line ms-auto my-3"></div>

    <div>
        <div class="w-25 ms-auto my-3 col">
            <p class="text-secondary">
                <span class="ms-1 me-2">&#x2022</span> Search With JQuery
            </p>
            <label class="visually-hidden" for="autoSizingInputGroup">Username</label>
            <div class="input-group">
                <div class="input-group-text bg-transparent" style="font-size: 15px"><i class="bi bi-search"></i></div>
                <input type="text" class="form-control" id="myInput" placeholder="Search here">
            </div>
        </div>

    </div>

    <div>

        <table class="table table-striped table-bordered table-responsive">
            <thead>
                <tr>
                    @*<th scope="col">CountryId</th>*@
                    <th scope="col" class="text-center">Branch Name</th>
                    <th scope="col" class="text-center">Branch Code</th>
                    <th scope="col" class="text-center">Created</th>
                    <th scope="col" class="text-center">Modified</th>
                    <th scope="col" class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody id="myTable">

                @foreach (DataRow dr in Model.Rows)
                {

                    <tr>
                        @*<td class="text-center">@dr["CountryID"]</td>*@
                        <td class="text-center">@dr["BranchName"]</td>
                        <td class="text-center">@dr["BranchCode"]</td>
                        <td class="text-center">@dr["Created"]</td>
                        <td class="text-center">@dr["Modified"]</td>
                        <td class="text-center d-flex justify-content-center align-items-center">

                            <form method="post" asp-area="Branch" asp-controller="MST_Branch" asp-action="MST_BranchAddEdit">
                                <input type="hidden" name="BranchID" value="@Convert.ToInt32(@dr["BranchID"])" />
                                <button type="submit" class="btn btn-primary py-1 me-2"><i class="bi bi-pen" style="font-size: 14px"></i></button>
                            </form>
                            <form method="post" asp-area="Branch" asp-controller="MST_Branch" asp-action="DeleteBranch">
                                <input type="hidden" name="BranchID" value="@Convert.ToInt32(@dr["BranchID"])" />
                                <button type="submit" class="btn btn-danger py-1"><i class="bi bi-trash" style="font-size: 14px"></i></button>
                            </form>

                        </td>
                    </tr>
                }

            </tbody>
        </table>

    </div>

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

@section Scripts {

    <script>
        $(document).ready(function () {
            //alert("Hello");
            $("#myInput").on("keyup", function () {
                //alert("Function");
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>

}