Student_Registration_Theme/Areas/State/Controllers/LOC_StateController.cs
using Microsoft.AspNetCore.Mvc;
using Student_Registration_Theme.Areas.Country.Models;
using Student_Registration_Theme.Areas.State.Models;
using System.Data;
using System.Data.SqlClient;

namespace Student_Registration.Areas.State.Controllers
{
    [Area("State")]
    public class LOC_StateController : Controller
    {

        private IConfiguration Configuration;

        public LOC_StateController(IConfiguration configuration)
        {
            Configuration = configuration;
        }


        public IActionResult LOC_StateList()
        {
            string connection_string = this.Configuration.GetConnectionString("MyConnectionString");
            SqlConnection conn = new SqlConnection(connection_string);
            conn.Open();

            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_LOC_State_SelectAll";

            SqlDataReader reader = cmd.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(reader);
            return View("LOC_StateList", dt);
        }

        public IActionResult Add()
        {
            return View("LOC_StateAddEdit");
        }

        public IActionResult LOC_StateAddEdit(int? StateID = 0)
        {
            string connecction_string = this.Configuration.GetConnectionString("MyConnectionString");

            SqlConnection conn2 = new SqlConnection(connecction_string);
            conn2.Open();

            SqlCommand cmd2 = conn2.CreateCommand();
            cmd2.CommandType = System.Data.CommandType.StoredProcedure;
            cmd2.CommandText = "PR_LOC_Country_ComboBox";

            SqlDataReader reader2 = cmd2.ExecuteReader();
            DataTable dt2 = new DataTable();
            dt2.Load(reader2);
            conn2.Close();

            List<LOC_Country_DropdownModel> list2 = new List<LOC_Country_DropdownModel>();

            foreach (DataRow dr2 in dt2.Rows)
            {
                LOC_Country_DropdownModel model2 = new LOC_Country_DropdownModel();
                model2.CountryID = Convert.ToInt32(dr2["CountryID"]);
                model2.CountryName = dr2["CountryName"].ToString();
                list2.Add(model2);
            }
            ViewBag.CountryList = list2;

            SqlConnection conn = new SqlConnection(connecction_string);
            conn.Open();

            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_LOC_State_SelectByPK";
            cmd.Parameters.AddWithValue("@StateID", StateID);
            SqlDataReader reader = cmd.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(reader);

            LOC_StateModel cm = new LOC_StateModel();

            foreach (DataRow row in dt.Rows)
            {
                cm.StateID = Convert.ToInt32(row["StateID"]);
                cm.StateName = row["StateName"].ToString();
                cm.StateCode = row["StateCode"].ToString();
                cm.CountryID = Convert.ToInt32(row["CountryID"]);
            }

            return View("LOC_StateAddEdit", cm);
        }

        public IActionResult LOC_StateSave(LOC_StateModel cm)
        {
            string connecction_string = this.Configuration.GetConnectionString("MyConnectionString");
            SqlConnection conn = new SqlConnection(connecction_string);
            conn.Open();

            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            if (cm.StateID == 0)
            {
                cmd.CommandText = "PR_LOC_State_Insert";
            }
            else
            {
                cmd.CommandText = "PR_LOC_State_UpdateByPK";
                cmd.Parameters.AddWithValue("@StateID", cm.StateID);
            }
            cmd.Parameters.AddWithValue("@StateName", cm.StateName);
            cmd.Parameters.AddWithValue("@StateCode", cm.StateCode);
            cmd.Parameters.AddWithValue("@CountryID", cm.CountryID);
            cmd.ExecuteNonQuery();
            conn.Close();

            return RedirectToAction("LOC_StateList");
        }

        public IActionResult DeleteState(int StateID)
        {
            string connection_string = this.Configuration.GetConnectionString("MyConnectionString");
            SqlConnection conn = new SqlConnection(connection_string);
            conn.Open();

            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_LOC_State_DeleteByPK";
            cmd.Parameters.AddWithValue("@StateID", StateID);
            cmd.ExecuteNonQuery();
            conn.Close();
            return RedirectToAction("LOC_StateList");
        }

        public IActionResult LOC_StateFilter(string? StateName, string? StateCode, string? CountryName)
        {

            string connection_string = this.Configuration.GetConnectionString("MyConnectionString");
            SqlConnection conn = new SqlConnection(connection_string);
            conn.Open();

            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_State_Filter";

            if (StateName == null)
            {
                StateName = DBNull.Value.ToString();
            }

            if (StateCode == null)
            {
                StateCode = DBNull.Value.ToString();
            }

            if (CountryName == null)
            {
                CountryName = DBNull.Value.ToString();
            }

            cmd.Parameters.AddWithValue("@StateName", StateName);
            cmd.Parameters.AddWithValue("@StateCode", StateCode);
            cmd.Parameters.AddWithValue("@CountryName", CountryName);

            SqlDataReader reader = cmd.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(reader);

            return View("LOC_StateList", dt);
        }

    }
}

Student_Registration_Theme/Areas/State/Views/LOC_State/LOC_StateAddEdit.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Student_Registration_Theme.Areas.State.Models.LOC_StateModel;
@using static System.Data.DataTable;
@using Student_Registration_Theme.Areas.Country.Models
@* @model System.Data.DataTable; *@


<div class="container border border-gray rounded p-5 shadow">

    <h2><i class="bi bi-gear me-2 pb-5" style="font-size: 25px"></i>State</h2>

    <hr />

    <form class="pt-3" method="post" asp-area="State" asp-controller="LOC_State" asp-action="LOC_StateSave">

        <div class="col my-4">
            <input type="text" class="form-control" asp-for="StateName" value="@Model.StateName" placeholder="State Name" aria-label="First name">
        </div>

        <div class="col my-4">
            <input type="text" class="form-control" asp-for="StateCode" value="@Model.StateCode" placeholder="State Code" aria-label="Last name">
        </div>

        <div class="col my-4 form-group">
            <select class="form-control" asp-for="CountryID" asp-items="@(new SelectList(ViewBag.CountryList,"CountryID","CountryName"))"><option>Select Countrty</option></select>
        </div>

        <div class="col mt-4">

            <input type="hidden" name="StateId" value="@Model.StateID" />
            <button class="btn btn-primary" type="submit">Submit</button>

        </div>

    </form>

</div>

Student_Registration_Theme/Areas/State/Views/LOC_State/LOC_StateList.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using System.Data;
@model System.Data.DataTable;

<div class="border rounded p-5 shadow">

    <div class="d-flex justify-content-between align-items-center">

        <h5 class="fw-bold"><i class="bi bi-gear me-2" style="font-size: 20px"></i>STATE LIST</h5>
        <a asp-area="State" asp-controller="LOC_State" asp-action="LOC_StateAddEdit">
            <button class="btn bg-success text-white py-2"><i class="bi bi-plus-circle me-2"></i>Add State</button>
        </a>

    </div>

    <hr />

    @*<div class="border border-dark rounded ps-3 pe-5 py-2 ms-auto w-25 my-3">

    Search here

    </div>*@

    @*<input type="text" placeholder="Search here" class="border border-dark d-block rounded ps-3 pe-5 py-2 ms-auto my-3" />*@

    <form asp-area="State" asp-controller="LOC_State">
        <div class="row">
            <div class="w-25 ms-auto my-3">
                <label class="visually-hidden" for="autoSizingInputGroup">Username</label>
                <div class="input-group">
                    <div class="input-group-text bg-transparent" style="font-size: 15px"><i class="bi bi-search"></i></div>
                    <input type="text" class="form-control" id="StateName" name="StateName" placeholder="Search State Name here">
                    @* <input type="hidden" name="StateName" value="StateName" />*@
                </div>
            </div>

            <div class="w-25 my-3">
                <label class="visually-hidden" for="autoSizingInputGroup">Username</label>
                <div class="input-group">
                    <div class="input-group-text bg-transparent" style="font-size: 15px"><i class="bi bi-search"></i></div>
                    <input type="text" class="form-control" id="StateCode" name="StateCode" placeholder="Search State Code here">
                    @*<input type="hidden" name="StateCode" value="StateCode" />*@
                </div>
            </div>

            <div class="w-25 ms-auto my-3">
                <label class="visually-hidden" for="autoSizingInputGroup">Username</label>
                <div class="input-group">
                    <div class="input-group-text bg-transparent" style="font-size: 15px"><i class="bi bi-search"></i></div>
                    <input type="text" class="form-control" id="CountryName" name="CountryName" placeholder="Search Country Name here">
                    @* <input type="hidden" name="CountryName" value="CountryName" />*@
                </div>
            </div>

            <div class="w-auto my-3">
                <div class="input-group">
                    <input type="submit" asp-action="LOC_StateFilter" class="btn btn-primary" id="" value="Apply Filter">
                </div>
            </div>

            <div class="w-auto my-3">
                <div class="input-group">
                    <input type="submit" asp-action="LOC_StateList" class="btn text-white" style="background-color: rgba(10 , 10 , 10 , 0.5)" id="" value="Clear Filter">
                </div>
            </div>

        </div>
    </form>

    <div class="line ms-auto my-3"></div>

    <div class="w-25 ms-auto my-3">
        <label class="visually-hidden" for="autoSizingInputGroup">Username</label>
        <div class="input-group">
            <div class="input-group-text bg-transparent" style="font-size: 15px"><i class="bi bi-search"></i></div>
            <input type="text" class="form-control" id = "myInput" placeholder="Search here">
        </div>
    </div>

    <div>

        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    @*<th scope="col">StateId</th>*@
                    <th scope="col" class="text-center">State Name</th>
                    <th scope="col" class="text-center">State Code</th>
                    <th scope="col" class="text-center">Country Name</th>
                    <th scope="col" class="text-center">Created</th>
                    <th scope="col" class="text-center">Modified</th>
                    <th scope="col" class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody id = "myTable">
                
                @foreach (DataRow dr in Model.Rows)
                {

                    <tr>
                        @*<td class="text-center">@dr["StateId"]</td>*@
                        <td class="text-center">@dr["StateName"]</td>
                        <td class="text-center">@dr["StateCode"]</td>
                        <td class="text-center">@dr["CountryName"]</td>
                        <td class="text-center">@dr["Created"]</td>
                        <td class="text-center">@dr["Modified"]</td>
                        <td class="text-center d-flex justify-content-center align-items-center">

                            <form asp-area="State" asp-controller="LOC_State" asp-action="LOC_StateAddEdit">
                                <input type ="hidden" name="StateId" value="@Convert.ToInt32(dr["StateId"])" />
                                <button type ="submit" class="btn btn-primary me-2 py-1"><i class="bi bi-pen" style="font-size: 14px"></i></button>
                            </form>
                            <form asp-area ="State" asp-controller ="LOC_State" asp-action ="DeleteState">
                                <input type ="hidden" name="StateId" value="@Convert.ToInt32(dr["StateId"])" />
                                <button type ="submit" class="btn btn-danger py-1"><i class="bi bi-trash" style="font-size: 14px"></i></button>
                            </form>

                        </td>
                    </tr>
                }

            </tbody>
        </table>

    </div>

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

@section Scripts {

    <script>
        $(document).ready(function () {
            //alert("Hello");
            $("#myInput").on("keyup", function () {
                //alert("Function");
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>

}