Student_Registration_Theme/Areas/Student/Controllers/MST_StudentController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using Student_Registration_Theme.Areas.Student.Models;
using Student_Registration_Theme.Areas.Branch.Models;
using Student_Registration_Theme.Areas.City.Models;

namespace Student_Registration_Theme.Areas.Student.Controllers
{
    [Area("Student")]
    public class MST_StudentController : Controller
    {
        public IConfiguration Configuration;

        public MST_StudentController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IActionResult MST_StudentList()
        {
            string connectionstring = this.Configuration.GetConnectionString("MyConnectionString");
            SqlConnection connection = new SqlConnection(connectionstring);

            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_MST_Student_SelectAll";
            SqlDataReader reader = command.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(reader);
            return View("MST_StudentList", dt);
        }

        public IActionResult MST_StudentSave(MST_StudentModel student)
        {
            string connectionstring = this.Configuration.GetConnectionString("MyConnectionString");
            SqlConnection connection = new SqlConnection(connectionstring);

            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;

            if (student.StudentID == null)
            {
                command.CommandText = "PR_MST_Student_Insert";
            }

            else
            {
                command.CommandText = "PR_MST_Student_UpdateByPK";
                command.Parameters.AddWithValue("@StudentID", student.StudentID);
            }

            command.Parameters.AddWithValue("@StudentName", student.StudentName);
            command.Parameters.AddWithValue("@BranchID", student.BranchID);
            command.Parameters.AddWithValue("@CityID", student.CityID);
            command.Parameters.AddWithValue("@MobileNoStudent", student.MobileNoStudent);
            command.Parameters.AddWithValue("@MobileNoFather", student.MobileNoFather);
            command.Parameters.AddWithValue("@Email", student.Email);
            command.Parameters.AddWithValue("@Address", student.Address);
            command.Parameters.AddWithValue("@BirthDate", student.BirthDate);
            command.Parameters.AddWithValue("@Age", student.Age);
            command.Parameters.AddWithValue("@IsActive", student.IsActive);
            command.Parameters.AddWithValue("@Gender", student.Gender);
            command.Parameters.AddWithValue("@Password", student.Password);

            command.ExecuteNonQuery();
            connection.Close();
            return RedirectToAction("MST_StudentList");
        }

        public IActionResult MST_StudentAddEdit(int StudentID = 0)
        {
            string connectionstring = this.Configuration.GetConnectionString("MyConnectionString");
            SqlConnection connection = new SqlConnection(connectionstring);

            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_MST_Student_SelectbyPK";
            command.Parameters.AddWithValue("@StudentID", StudentID);

            SqlDataReader reader = command.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(reader);

            MST_StudentModel student = new MST_StudentModel();

            foreach (DataRow row in dt.Rows)
            {
                student.StudentID = Convert.ToInt32(row["StudentID"]);
                student.StudentName = row["StudentName"].ToString();
                student.BranchID = Convert.ToInt32(row["BranchID"]);
                student.CityID = Convert.ToInt32(row["CityID"]);
                student.MobileNoStudent = row["MobileNoStudent"].ToString();
                student.MobileNoFather = row["MobileNoFather"].ToString();
                student.Email = row["Email"].ToString();
                student.Address = row["Address"].ToString();
                student.BirthDate = Convert.ToDateTime(row["BirthDate"]);
                student.IsActive = Convert.ToBoolean(row["IsActive"]);
                student.Age = Convert.ToInt32(row["Age"]);
                student.Gender = row["Gender"].ToString();
                student.Password = row["Password"].ToString();

            }

            SqlConnection connection2 = new SqlConnection(connectionstring);
            connection2.Open();
            SqlCommand command2 = connection2.CreateCommand();
            command2.CommandType = CommandType.StoredProcedure;
            command2.CommandText = "PR_MST_BranchComboBox";
            SqlDataReader reader2 = command2.ExecuteReader();
            DataTable dt2 = new DataTable();
            dt2.Load(reader2);
            connection2.Close();

            List<MST_BranchDropdownModel> list2 = new List<MST_BranchDropdownModel>();

            foreach (DataRow dr in dt2.Rows)
            {
                MST_BranchDropdownModel model = new MST_BranchDropdownModel();
                model.BranchID = Convert.ToInt32(dr["BranchID"]);
                model.BranchName = dr["BranchName"].ToString();
                list2.Add(model);
            }

            ViewBag.BranchList = list2;

            SqlConnection connection3 = new SqlConnection(connectionstring);
            connection3.Open();
            SqlCommand command3 = connection3.CreateCommand();
            command3.CommandType = CommandType.StoredProcedure;
            command3.CommandText = "PR_LOC_CityComboBox";
            SqlDataReader reader3 = command3.ExecuteReader();
            DataTable dt3 = new DataTable();
            dt3.Load(reader3);
            connection3.Close();

            List<LOC_CityDropdownModel> list3 = new List<LOC_CityDropdownModel>();

            foreach (DataRow dr in dt3.Rows)
            {
                LOC_CityDropdownModel model = new LOC_CityDropdownModel();
                model.CityID = Convert.ToInt32(dr["CityID"]);
                model.CityName = dr["CityName"].ToString();
                list3.Add(model);
            }

            ViewBag.CityList = list3;

            return View(student);
        }

        public IActionResult StudentDelete(int StudentID)
        {
            string connectionstring = this.Configuration.GetConnectionString("MyConnectionString");
            SqlConnection connection = new SqlConnection(connectionstring);

            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_MST_Student_DeleteByPK";
            command.Parameters.AddWithValue("@StudentID", StudentID);
            command.ExecuteNonQuery();
            connection.Close();
            return RedirectToAction("StudentList");
        }

        public IActionResult MST_StudentFilter(string? StudentName, string? BranchName, string? CityName, string? StateName, string? CountryName)
        {

            string connection_string = this.Configuration.GetConnectionString("MyConnectionString");
            SqlConnection conn = new SqlConnection(connection_string);
            conn.Open();

            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_Student_Filter";

            if (StudentName == null)
            {
                StudentName = DBNull.Value.ToString();
            }

            if (BranchName == null)
            {
                BranchName = DBNull.Value.ToString();
            }

            if (CityName == null)
            {
                CityName = DBNull.Value.ToString();
            }

            if (StateName == null)
            {
                StateName = DBNull.Value.ToString();
            }

            if (CountryName == null)
            {
                CountryName = DBNull.Value.ToString();
            }

            cmd.Parameters.AddWithValue("@StudentName", StudentName);
            cmd.Parameters.AddWithValue("@BranchName", BranchName);
            cmd.Parameters.AddWithValue("@CityName", CityName);
            cmd.Parameters.AddWithValue("@StateName", StateName);
            cmd.Parameters.AddWithValue("@CountryName", CountryName);

            SqlDataReader reader = cmd.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(reader);

            return View("MST_StudentList", dt);
        }
    }
}

Student_Registration_Theme/Areas/Student/Views/MST_Student/MST_StudentAddEdit.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Student_Registration_Theme.Areas.Student.Models.MST_StudentModel;

<div class="container border border-gray rounded p-5 shadow">

    <h2><i class="bi bi-gear me-2 pb-5" style="font-size: 25px"></i>Student</h2>

    <hr />

    <form class="pt-3" method="post" asp-area="Student" asp-controller="MST_Student" asp-action="MST_StudentSave">

        <div class="col my-4">
            <input type="text" class="form-control" asp-for="StudentName" placeholder="Student Name" aria-label="First name">
        </div>

        <div class="col my-4 form-group">
            <label>Branch</label>
            <select class="form-control" asp-for="BranchID" asp-items="@(new SelectList(ViewBag.BranchList,"BranchID" , "BranchName"))">
                <option>Select Branch</option>
            </select>
            <span asp-validation-for="BranchID" class="text-danger"></span>
        </div>

        <div class="col my-4 form-group">
            <label>City</label>
            <select class="form-control" asp-for="CityID" asp-items="@(new SelectList(ViewBag.CityList,"CityID" , "CityName"))">
                <option>Select City</option>
            </select>
            <span asp-validation-for="CityID" class="text-danger"></span>
        </div>

        <div class="col my-4">
            <label> Student Mobile no.</label>
            <input type="text" placeholder="Enter Student Mobile no." asp-for="MobileNoStudent" class="form-control" value="@Model.MobileNoStudent" />
            <span asp-validation-for="MobileNoStudent" class="text-danger"></span>
        </div>

        <div class="col my-4">
            <label> Email</label>
            <input type="text" placeholder="Enter Email" asp-for="Email" class="form-control" value="@Model.Email" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>

        <div class="col my-4">
            <label> Father Mobile no.</label>
            <input type="text" placeholder="Enter Father's Mobile no.'" asp-for="MobileNoFather" class="form-control" value="@Model.MobileNoFather" />
            <span asp-validation-for="MobileNoFather" class="text-danger"></span>
        </div>

        <div class="col my-4">
            <label> Address</label>
            <textarea class="form-control" placeholder="Enter Address" asp-for="Address">@Model.Address</textarea>
            <span asp-validation-for="Address" class="text-danger"></span>
            @* <input type="text" placeholder="Enter Country name" asp-for="StudentName" class="form-control" value="@Model.StudentName" /> *@
        </div>

        <div class="col my-4">
            <label> Birth Date</label>
            <input type="text" placeholder="Enter Birthdate" asp-for="BirthDate" class="form-control" value="@Convert.ToDateTime(Model.BirthDate)" />
            <span asp-validation-for="BirthDate" class="text-danger"></span>
        </div>

        <div class="col my-4">
            <label> Age</label>
            <input type="text" placeholder="Enter Age" asp-for="Age" class="form-control" value="@Model.Age" />
            <span asp-validation-for="Age" class="text-danger"></span>
        </div>

        <div class="col my-4">
            <label> Is Active</label>
            <input type="text" placeholder="IS Active True or False" asp-for="IsActive" class="form-control" value="@Convert.ToBoolean(Model.IsActive)" />
            <span asp-validation-for="IsActive" class="text-danger"></span>
        </div>

        <div class="col my-4">
            <label> Gender</label>
            <input type="text" placeholder="Enter Gender" asp-for="Gender" class="form-control" value="@Model.Gender" />
            <span asp-validation-for="Gender" class="text-danger"></span>
        </div>

        <div class="col my-4">
            <label> Password</label>
            <input type="text" placeholder="Enter Password" asp-for="Password" class="form-control" value="@Model.Password" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>

        <div class="col mt-4">

            <input type="hidden" name="StudentID" value="@Model.StudentID" />
            <button class="btn btn-primary" type="submit">Submit</button>

        </div>

    </form>

</div>

Student_Registration_Theme/Areas/Student/Views/MST_Student/MST_StudentList.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using System.Data;
@model System.Data.DataTable;

<style>

    .line {
        width: 50%;
        height: 1px;
        border: 1px solid rgba(0, 0, 0, 0.1);
    }

</style>

<div class="pagetitle my-4 mx-2">
    <h1>Dashboard</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">Student</li>
        </ol>
    </nav>
</div><!-- End Page Title -->

<div class="border rounded p-5 shadow">

    <div class="d-flex justify-content-between align-items-center">

        <h5 class="fw-bold"><i class="bi bi-gear me-2" style="font-size: 20px"></i>BRANCH LIST</h5>
        <a asp-area="Student" asp-controller="MST_Student" asp-action="MST_StudentAddEdit">
            <button class="btn bg-success text-white py-2"><i class="bi bi-plus-circle me-2"></i>ADD STUDENT</button>
        </a>

    </div>

    <hr />

    @*<div class="border border-dark rounded ps-3 pe-5 py-2 ms-auto w-25 my-3">

    Search here

    </div>*@

    @*<input type="text" placeholder="Search here" class="border border-dark d-block rounded ps-3 pe-5 py-2 ms-auto my-3" />*@

    <form asp-area="Stundet" asp-controller="MST_Student">
        <div class="row">
            <div class="w-25 ms-auto my-3">
                <label class="visually-hidden" for="autoSizingInputGroup">Username</label>
                <div class="input-group">
                    <div class="input-group-text bg-transparent" style="font-size: 15px"><i class="bi bi-search"></i></div>
                    <input type="text" class="form-control" id="StudentName" name="StudentName" placeholder="Search Student Name here">
                    @* <input type="hidden" name="BranchName" value="BranchName" />*@
                </div>
            </div>

            <div class="w-25 my-3">
                <label class="visually-hidden" for="autoSizingInputGroup">Username</label>
                <div class="input-group">
                    <div class="input-group-text bg-transparent" style="font-size: 15px"><i class="bi bi-search"></i></div>
                    <input type="text" class="form-control" id="BranchName" name="BranchName" placeholder="Search Branch Name here">
                    @*<input type="hidden" name="BranchCode" value="BranchCode" />*@
                </div>
            </div>

            <div class="w-25 my-3">
                <label class="visually-hidden" for="autoSizingInputGroup">Username</label>
                <div class="input-group">
                    <div class="input-group-text bg-transparent" style="font-size: 15px"><i class="bi bi-search"></i></div>
                    <input type="text" class="form-control" id="CityName" name="CityName" placeholder="Search City Name here">
                    @*<input type="hidden" name="BranchCode" value="BranchCode" />*@
                </div>
            </div>

            <div class="w-25 my-3">
                <label class="visually-hidden" for="autoSizingInputGroup">Username</label>
                <div class="input-group">
                    <div class="input-group-text bg-transparent" style="font-size: 15px"><i class="bi bi-search"></i></div>
                    <input type="text" class="form-control" id="StateName" name="StateName" placeholder="Search State Name here">
                    @*<input type="hidden" name="BranchCode" value="BranchCode" />*@
                </div>
            </div>

            <div class="w-25 my-3">
                <label class="visually-hidden" for="autoSizingInputGroup">Username</label>
                <div class="input-group">
                    <div class="input-group-text bg-transparent" style="font-size: 15px"><i class="bi bi-search"></i></div>
                    <input type="text" class="form-control" id="CountryName" name="CountryName" placeholder="Search Country Name here">
                    @*<input type="hidden" name="BranchCode" value="BranchCode" />*@
                </div>
            </div>

            <div class="w-auto my-3">
                <div class="input-group">
                    <input type="submit" asp-action="MST_StudentFilter" class="btn btn-primary" id="" value="Apply Filter" placeholder="Search Country Code here">
                </div>
            </div>

            <div class="w-auto my-3">
                <div class="input-group">
                    <input type="submit" asp-action="MST_StudentList" class="btn text-white" style="background-color: rgba(10 , 10 , 10 , 0.5)" id="" value="Clear Filter" placeholder="Search Country Code here">
                </div>
            </div>

        </div>
    </form>

    <div class="line ms-auto my-3"></div>

    <div>
        <div class="w-25 ms-auto my-3 col">
            <p class="text-secondary">
                <span class="ms-1 me-2">&#x2022</span> Search With JQuery
            </p>
            <label class="visually-hidden" for="autoSizingInputGroup">Username</label>
            <div class="input-group">
                <div class="input-group-text bg-transparent" style="font-size: 15px"><i class="bi bi-search"></i></div>
                <input type="text" class="form-control" id="myInput" placeholder="Search here">
            </div>
        </div>

    </div>

    <div>

        <table class="table table-striped table-bordered table-responsive">
            <thead>
                <tr>
                    @*<th scope="col">CountryId</th>*@
                    <th scope="col" class="text-center">Student Name</th>
                    <th scope="col" class="text-center">Branch Name</th>
                    <th scope="col" class="text-center">City Name</th>
                    <th scope="col" class="text-center">State Name</th>
                    <th scope="col" class="text-center">Country Name</th>
                    <th scope="col" class="text-center">Mo. No. of Student</th>
                    <th scope="col" class="text-center">Email</th>
                    <th scope="col" class="text-center">Created</th>
                    <th scope="col" class="text-center">Modified</th>
                    <th scope="col" class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody id="myTable">

                @foreach (DataRow dr in Model.Rows)
                {

                    <tr>
                        <td class="text-center">@dr["StudentName"]</td>
                        <td class="text-center">@dr["BranchName"]</td>
                        <td class="text-center">@dr["CityName"]</td>
                        <td class="text-center">@dr["StateName"]</td>
                        <td class="text-center">@dr["CountryName"]</td>
                        <td class="text-center">@dr["MobileNoStudent"]</td>
                        <td class="text-center">@dr["Email"]</td>
                        <td class="text-center">@dr["Created"]</td>
                        <td class="text-center">@dr["Modified"]</td>
                        <td class="text-center d-flex justify-content-center align-items-center">

                            <form method="post" asp-area="Student" asp-controller="MST_Student" asp-action="MST_StudentAddEdit">
                                <input type="hidden" name="StudentID" value="@Convert.ToInt32(@dr["StudentID"])" />
                                <button type="submit" class="btn btn-primary py-1 me-2"><i class="bi bi-pen" style="font-size: 14px"></i></button>
                            </form>
                            <form method="post" asp-area="Student" asp-controller="MST_Student" asp-action="DeleteStudent">
                                <input type="hidden" name="StudentID" value="@Convert.ToInt32(@dr["StudentID"])" />
                                <button type="submit" class="btn btn-danger py-1"><i class="bi bi-trash" style="font-size: 14px"></i></button>
                            </form>

                        </td>
                    </tr>
                }

            </tbody>
        </table>

    </div>

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

@section Scripts {

    <script>
        $(document).ready(function () {
            //alert("Hello");
            $("#myInput").on("keyup", function () {
                //alert("Function");
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>

}